trigger:
  - main

name: Deploy Bicep files





steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      useGlobalConfig: false
      inlineScript: |
        az --version

        az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters sqlServerAdministratorLogin=$(SQLSERVERADMINISTRATORLOGIN) sqlServerAdministratorLoginPassword=$(SQLSERVERADMINISTRATORLOGINPASSWORD)

